version: "3.8"

services:
  nginx:
     build: ./requirements/nginx
     image: nginx
     container_name: nginx_inception
     ports:
       - "443:443"
     volumes:
       - html:/var/www/html
     networks:
       - inception
     depends_on:
       - wordpress
     restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    image: wp
    container_name: wordpress_inception
    volumes:
      - html:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: db_inception
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped

volumes:
  html:
    driver: local
    driver_opts:
      type: none
      device: /home/delvira-/data/html
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/delvira-/data/database
      o: bind

networks:
  inception:
    driver: bridge