CREATE DATABASE IF NOT EXISTS mariadb;
CREATE USER IF NOT EXISTS 'delvira-'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON mariadb.* TO 'delvira-'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '12345';